# Generated by Django 4.2.1 on 2023-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
