# Generated by Django 4.2.1 on 2023-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_patient_description_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
