debug: true
secret_key: 'YOUR_SECRET_KEY_HERE'

database:
    engine: 'django.db.backends.sqlite3'
    name: 'db.sqlite3'

seeding:
    customer_qty: 5     # Number of customers to seed
    date_qty: 30        # Number of dates to generate dates for
    time_start: 8       # Start time for spots (from 0 to 24)
    time_end: 23        # End time for spots (from 0 to 24)
    time_step: 2        # Interval between times
    booking_share: 0.5  # Share of spots that should be booked (from 0 to 1)
