# Generated by Django 4.2.1 on 2023-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('spot',)},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ('customer', 'date', 'time')},
        ),
        migrations.AddConstraint(
            model_name='spot',
            constraint=models.UniqueConstraint(fields=('customer', 'date', 'time'), name='unique_spot'),
        ),
    ]
