# Generated by Django 4.2.1 on 2023-06-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_options_alter_spot_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spot',
            name='unique_spot',
        ),
    ]
