# Generated by Django 4.2.1 on 2023-06-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_spot_unique_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.spot'),
        ),
    ]
